import React, { useState, useEffect } from 'react';
import { CreditCard as Edit, Trash2, UserCheck, UserX } from 'lucide-react';
import DataTable from '../components/DataTable';
import FilterBar, { FilterConfig } from '../components/FilterBar';
import CrudModal from '../components/CrudModal';
import ConfirmationModal from '../components/ConfirmationModal';
import { updateCustomer, deleteCustomer, getSalesReps } from '../api/supabaseHelpers';
import { AdminCustomer, AdminUser, PaginationParams } from '../../../types';
import { usePaginatedData } from '../hooks/useAdminData';
import { getCustomers } from '../api/supabaseHelpers';
import { toast } from '../../../core/utils/toast';